# Generated by Django 4.2 on 2023-05-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
