# Generated by Django 3.2 on 2023-05-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.product'),
            preserve_default=False,
        ),
    ]
