# Generated by Django 3.2 on 2023-05-13 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.coupon'),
            preserve_default=False,
        ),
    ]
