# Generated by Django 3.2 on 2023-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
