# Generated by Django 4.2 on 2023-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_shopdetail_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
