# Generated by Django 3.2 on 2023-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_orderdetail_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
