# Generated by Django 3.2 on 2023-05-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.shop'),
            preserve_default=False,
        ),
    ]
