# Generated by Django 3.2 on 2023-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_shopdetail_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
