# Generated by Django 4.2 on 2023-05-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
