# Generated by Django 4.2 on 2023-05-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paypal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
