from django.urls import path, include
from .views import *

urlpatterns = [
    path('', lambda request: redirect('home'), name='root'),
    path('home', HomeView.as_view(), name='home'),
    path('login/', login_view, name='login'),
    path('signup', signup_view, name='signup'),
    path('cart', cart, name='cart'),
    path('add_to_cart/<int:product_id>', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>', remove_from_cart, name='remove_from_cart'),
    path('product/<int:product_id>/', productdetail, name='product_detail'),
    path('checkout', checkout, name='checkout'),
    path('checkout-paypal', checkout_paypal, name='checkout_paypal'),
    path('sendcheckout', sendcheckout, name='sendcheckout'),
    path('profile', profile, name='profile'),
    path('order', order, name='order'),
    path('shop/<int:page>', shop, name='shop'),
    path('shop-rating/<int:page>', shop_rating, name='shop_rating'),
    path('shop-popularity/<int:page>', shop_popularity, name='shop_popularity'),
    path('contact', contact, name='contact'),
    path('update-profile', update_profile, name='updateprofile'),
    path('add-favorite/<int:product_id>', addfavorite, name='addfavorite'),
    path('favorite', favorite, name='favorite'),
    path('add-comment/<int:product_id>', addcomment, name='addcomment'),
    path('become-host', becomehost, name='becomehost'),
    path('create-shop', createshop, name='createshop'),
    path('add-product', addproduct, name='addproduct'),
    path('add-product-send', createproduct, name='createproduct'),
    path('my-shop', shopdetail, name='shopdetail'),
    path('remove_from_shop/<int:shop_detail_id>', remove_from_shop, name='remove_from_shop'),
    path('edit-product/<int:product_id>/', editproduct, name='editproduct'),
    path('edit-product-send', editproductsend, name='editproductsend'),
    path('order-shop', ordershop, name='ordershop'),
    path('edit-order-detail', editordershop, name='editordershop'),
    path('filter', filter, name='filter'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed', payment_complete, name='payment_complete'),
    path('payment-failed', payment_failed, name='payment_failed'),
    path('payment-process', payment_process, name='payment_process'),
    path('checkout-paypal-success', checkout_paypal_success, name='checkout_paypal_success'),
    path('logout/', logout_view, name='logout'),
    path('search/', search_results, name='search_results'),
    path('shop-profile', shop_profile, name='shop_profile'),
    path('update-shop', update_shop, name='updateshop'),
    path('rating/<int:product_id>/<int:rating>', rating, name='rating')
]